// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#pragma once

#include "LensSerialZoom_s.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class LensSerialZoomS final {
public:
    using CppType = ::eo_api::LensSerialZoomS;
    using JniType = jobject;

    using Boxed = LensSerialZoomS;

    ~LensSerialZoomS();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    LensSerialZoomS();
    friend ::djinni::JniClass<LensSerialZoomS>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/srcinc/eo_api/LensSerialZoomS") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(SBBBBBBBBBBDDDS)V") };
    const jfieldID field_LensType { ::djinni::jniGetFieldID(clazz.get(), "LensType", "S") };
    const jfieldID field_LensID { ::djinni::jniGetFieldID(clazz.get(), "LensID", "B") };
    const jfieldID field_VideoSource { ::djinni::jniGetFieldID(clazz.get(), "VideoSource", "B") };
    const jfieldID field_SerialPort { ::djinni::jniGetFieldID(clazz.get(), "SerialPort", "B") };
    const jfieldID field_ZoomCmd { ::djinni::jniGetFieldID(clazz.get(), "ZoomCmd", "B") };
    const jfieldID field_FocusCmd { ::djinni::jniGetFieldID(clazz.get(), "FocusCmd", "B") };
    const jfieldID field_IrisCmd { ::djinni::jniGetFieldID(clazz.get(), "IrisCmd", "B") };
    const jfieldID field_IrisAuto { ::djinni::jniGetFieldID(clazz.get(), "IrisAuto", "B") };
    const jfieldID field_ZoomCal { ::djinni::jniGetFieldID(clazz.get(), "ZoomCal", "B") };
    const jfieldID field_UseOldProtocol { ::djinni::jniGetFieldID(clazz.get(), "UseOldProtocol", "B") };
    const jfieldID field_Enable2X { ::djinni::jniGetFieldID(clazz.get(), "Enable2X", "B") };
    const jfieldID field_ZoomFov { ::djinni::jniGetFieldID(clazz.get(), "ZoomFov", "D") };
    const jfieldID field_MinFov { ::djinni::jniGetFieldID(clazz.get(), "MinFov", "D") };
    const jfieldID field_MaxFov { ::djinni::jniGetFieldID(clazz.get(), "MaxFov", "D") };
    const jfieldID field_FocusPosition { ::djinni::jniGetFieldID(clazz.get(), "FocusPosition", "S") };
};

}  // namespace djinni_generated
