// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#include "LensConfig_s.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

LensConfigS::LensConfigS() = default;

LensConfigS::~LensConfigS() = default;

auto LensConfigS::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<LensConfigS>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.Analog1)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.Analog2)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.Analog3)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.Analog4)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.Digital1)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.Digital2)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto LensConfigS::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 7);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<LensConfigS>::get();
    return {::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_Analog1)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_Analog2)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_Analog3)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_Analog4)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_Digital1)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_Digital2))};
}

}  // namespace djinni_generated
