// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#include "NativeEOAPILib.hpp"  // my header
#include "Marshal.hpp"
#include "NativeLensConfigS.hpp"
#include "NativeLensSerialIRZoomS.hpp"
#include "NativeLensSerialZoomS.hpp"
#include "NativeZoomToRangeConfigS.hpp"

namespace djinni_generated {

NativeEOAPILib::NativeEOAPILib() : ::djinni::JniInterface<::helloworld::EOAPILib, NativeEOAPILib>("com/mycompany/helloworld/EOAPILib$CppProxy") {}

NativeEOAPILib::~NativeEOAPILib() = default;


CJNIEXPORT void JNICALL Java_com_mycompany_helloworld_EOAPILib_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::helloworld::EOAPILib>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_mycompany_helloworld_EOAPILib_ILens(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        ::helloworld::EOAPILib::ILens();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_mycompany_helloworld_EOAPILib_00024CppProxy_native_1SetSerialZoom(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_zoom)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::helloworld::EOAPILib>(nativeRef);
        ref->SetSerialZoom(::djinni_generated::NativeLensSerialZoomS::toCpp(jniEnv, j_zoom));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jshort JNICALL Java_com_mycompany_helloworld_EOAPILib_00024CppProxy_native_1QueryAllLensConfig(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jshort j_serialIRType)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::helloworld::EOAPILib>(nativeRef);
        auto r = ref->QueryAllLensConfig(::djinni::I16::toCpp(jniEnv, j_serialIRType));
        return ::djinni::release(::djinni::I16::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_mycompany_helloworld_EOAPILib_00024CppProxy_native_1ParseSerialZoomConfigMessage(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jbyte j_data)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::helloworld::EOAPILib>(nativeRef);
        auto r = ref->ParseSerialZoomConfigMessage(::djinni::I8::toCpp(jniEnv, j_data));
        return ::djinni::release(::djinni_generated::NativeLensSerialZoomS::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_mycompany_helloworld_EOAPILib_00024CppProxy_native_1SetSerialIRZoom(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_zoom)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::helloworld::EOAPILib>(nativeRef);
        ref->SetSerialIRZoom(::djinni_generated::NativeLensSerialIRZoomS::toCpp(jniEnv, j_zoom));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_mycompany_helloworld_EOAPILib_00024CppProxy_native_1ParseSerialIRZoomConfigMessage(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jbyte j_data)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::helloworld::EOAPILib>(nativeRef);
        auto r = ref->ParseSerialIRZoomConfigMessage(::djinni::I8::toCpp(jniEnv, j_data));
        return ::djinni::release(::djinni_generated::NativeLensSerialIRZoomS::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_mycompany_helloworld_EOAPILib_00024CppProxy_native_1SetZoomToRange(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_config)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::helloworld::EOAPILib>(nativeRef);
        ref->SetZoomToRange(::djinni_generated::NativeZoomToRangeConfigS::toCpp(jniEnv, j_config));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_mycompany_helloworld_EOAPILib_00024CppProxy_native_1ParseZoomToRangeConfigMessage(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jbyte j_data)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::helloworld::EOAPILib>(nativeRef);
        auto r = ref->ParseZoomToRangeConfigMessage(::djinni::I8::toCpp(jniEnv, j_data));
        return ::djinni::release(::djinni_generated::NativeZoomToRangeConfigS::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_mycompany_helloworld_EOAPILib_00024CppProxy_native_1SetConnectionID(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jshort j_connectionID)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::helloworld::EOAPILib>(nativeRef);
        ref->SetConnectionID(::djinni::I16::toCpp(jniEnv, j_connectionID));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_mycompany_helloworld_EOAPILib_00024CppProxy_native_1SetLensConfig(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_config)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::helloworld::EOAPILib>(nativeRef);
        ref->SetLensConfig(::djinni_generated::NativeLensConfigS::toCpp(jniEnv, j_config));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_mycompany_helloworld_EOAPILib_00024CppProxy_native_1ParseLensConfigMessage(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jbyte j_data)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::helloworld::EOAPILib>(nativeRef);
        auto r = ref->ParseLensConfigMessage(::djinni::I8::toCpp(jniEnv, j_data));
        return ::djinni::release(::djinni_generated::NativeLensConfigS::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
