// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#pragma once

#include "LensSerialZoom_s.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeLensSerialZoomS final {
public:
    using CppType = ::helloworld::LensSerialZoomS;
    using JniType = jobject;

    using Boxed = NativeLensSerialZoomS;

    ~NativeLensSerialZoomS();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeLensSerialZoomS();
    friend ::djinni::JniClass<NativeLensSerialZoomS>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/mycompany/helloworld/LensSerialZoomS") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(SBBBBBBBBBBDDDS)V") };
    const jfieldID field_mLensType { ::djinni::jniGetFieldID(clazz.get(), "mLensType", "S") };
    const jfieldID field_mLensID { ::djinni::jniGetFieldID(clazz.get(), "mLensID", "B") };
    const jfieldID field_mVideoSource { ::djinni::jniGetFieldID(clazz.get(), "mVideoSource", "B") };
    const jfieldID field_mSerialPort { ::djinni::jniGetFieldID(clazz.get(), "mSerialPort", "B") };
    const jfieldID field_mZoomCmd { ::djinni::jniGetFieldID(clazz.get(), "mZoomCmd", "B") };
    const jfieldID field_mFocusCmd { ::djinni::jniGetFieldID(clazz.get(), "mFocusCmd", "B") };
    const jfieldID field_mIrisCmd { ::djinni::jniGetFieldID(clazz.get(), "mIrisCmd", "B") };
    const jfieldID field_mIrisAuto { ::djinni::jniGetFieldID(clazz.get(), "mIrisAuto", "B") };
    const jfieldID field_mZoomCal { ::djinni::jniGetFieldID(clazz.get(), "mZoomCal", "B") };
    const jfieldID field_mUseOldProtocol { ::djinni::jniGetFieldID(clazz.get(), "mUseOldProtocol", "B") };
    const jfieldID field_mEnable2X { ::djinni::jniGetFieldID(clazz.get(), "mEnable2X", "B") };
    const jfieldID field_mZoomFov { ::djinni::jniGetFieldID(clazz.get(), "mZoomFov", "D") };
    const jfieldID field_mMinFov { ::djinni::jniGetFieldID(clazz.get(), "mMinFov", "D") };
    const jfieldID field_mMaxFov { ::djinni::jniGetFieldID(clazz.get(), "mMaxFov", "D") };
    const jfieldID field_mFocusPosition { ::djinni::jniGetFieldID(clazz.get(), "mFocusPosition", "S") };
};

}  // namespace djinni_generated
