// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#include "NativeLensSerialIRZoomS.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeLensSerialIRZoomS::NativeLensSerialIRZoomS() = default;

NativeLensSerialIRZoomS::~NativeLensSerialIRZoomS() = default;

auto NativeLensSerialIRZoomS::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeLensSerialIRZoomS>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.LensType)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.VideoSource)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.SerialPort)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.ZoomCmd)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.ZoomCal)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.FocusCmd)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.Polarity)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.AGC)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.DayMode)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.HighSensitivity)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.AutoCalibration)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.LensCover)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.FlirMenuCommand)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.ManualGain)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.ManualOffset)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.NonUniformityCorrectionTable)),
                                                           ::djinni::get(::djinni::F64::fromCpp(jniEnv, c.ZoomFov)),
                                                           ::djinni::get(::djinni::F64::fromCpp(jniEnv, c.MinFov)),
                                                           ::djinni::get(::djinni::F64::fromCpp(jniEnv, c.MaxFov)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.FocusPosition)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeLensSerialIRZoomS::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 21);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeLensSerialIRZoomS>::get();
    return {::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_mLensType)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_mVideoSource)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_mSerialPort)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_mZoomCmd)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_mZoomCal)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_mFocusCmd)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_mPolarity)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_mAGC)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_mDayMode)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_mHighSensitivity)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_mAutoCalibration)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_mLensCover)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_mFlirMenuCommand)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_mManualGain)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_mManualOffset)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_mNonUniformityCorrectionTable)),
            ::djinni::F64::toCpp(jniEnv, jniEnv->GetDoubleField(j, data.field_mZoomFov)),
            ::djinni::F64::toCpp(jniEnv, jniEnv->GetDoubleField(j, data.field_mMinFov)),
            ::djinni::F64::toCpp(jniEnv, jniEnv->GetDoubleField(j, data.field_mMaxFov)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_mFocusPosition))};
}

}  // namespace djinni_generated
