// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#include "NativeLensConfigS.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeLensConfigS::NativeLensConfigS() = default;

NativeLensConfigS::~NativeLensConfigS() = default;

auto NativeLensConfigS::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeLensConfigS>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.Analog1)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.Analog2)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.Analog3)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.Analog4)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.Digital1)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.Digital2)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeLensConfigS::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 7);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeLensConfigS>::get();
    return {::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_mAnalog1)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_mAnalog2)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_mAnalog3)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_mAnalog4)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_mDigital1)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_mDigital2))};
}

}  // namespace djinni_generated
