// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#include "ZoomToRangeConfig_s.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

ZoomToRangeConfigS::ZoomToRangeConfigS() = default;

ZoomToRangeConfigS::~ZoomToRangeConfigS() = default;

auto ZoomToRangeConfigS::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<ZoomToRangeConfigS>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.VideoSource)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.Enable)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.UseSinglePointAlgorithm)),
                                                           ::djinni::get(::djinni::F64::fromCpp(jniEnv, c.MinLensFOV)),
                                                           ::djinni::get(::djinni::F64::fromCpp(jniEnv, c.MaxLensFOV)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.MinRange)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.MaxRange)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto ZoomToRangeConfigS::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 8);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<ZoomToRangeConfigS>::get();
    return {::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_VideoSource)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_Enable)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_UseSinglePointAlgorithm)),
            ::djinni::F64::toCpp(jniEnv, jniEnv->GetDoubleField(j, data.field_MinLensFOV)),
            ::djinni::F64::toCpp(jniEnv, jniEnv->GetDoubleField(j, data.field_MaxLensFOV)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_MinRange)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_MaxRange))};
}

}  // namespace djinni_generated
