// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

package com.mycompany.helloworld;

/** ---------- Lens Config Message Structure ---------- */
public final class LensConfigS {


    /*package*/ final short mAnalog1;

    /*package*/ final short mAnalog2;

    /*package*/ final short mAnalog3;

    /*package*/ final short mAnalog4;

    /*package*/ final short mDigital1;

    /*package*/ final short mDigital2;

    public LensConfigS(
            short Analog1,
            short Analog2,
            short Analog3,
            short Analog4,
            short Digital1,
            short Digital2) {
        this.mAnalog1 = Analog1;
        this.mAnalog2 = Analog2;
        this.mAnalog3 = Analog3;
        this.mAnalog4 = Analog4;
        this.mDigital1 = Digital1;
        this.mDigital2 = Digital2;
    }

    public short getAnalog1() {
        return mAnalog1;
    }

    /** lens connected to analog video source 1 */
    public short getAnalog2() {
        return mAnalog2;
    }

    /** lens connected to analog video source 2 */
    public short getAnalog3() {
        return mAnalog3;
    }

    /**
     * lens connected to analog video source 3
     * (differential input on Model 6005 R2)
     */
    public short getAnalog4() {
        return mAnalog4;
    }

    /**
     * lens connected to analog video source 4
     * (not available on Model 6005 R2)
     */
    public short getDigital1() {
        return mDigital1;
    }

    /**
     * lens connected to digital video source 1
     * lens connected to digital video source 2
     * (not available on Model 6005 and only
     *  supported on 6007 with daughter card)
     */
    public short getDigital2() {
        return mDigital2;
    }

    @Override
    public String toString() {
        return "LensConfigS{" +
                "mAnalog1=" + mAnalog1 +
                "," + "mAnalog2=" + mAnalog2 +
                "," + "mAnalog3=" + mAnalog3 +
                "," + "mAnalog4=" + mAnalog4 +
                "," + "mDigital1=" + mDigital1 +
                "," + "mDigital2=" + mDigital2 +
        "}";
    }

}
