// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

package com.srcinc.eo_api;

/** ---------- Lens Config Message Structure ---------- */
public final class LensConfigS {


    /*package*/ final short Analog1;

    /*package*/ final short Analog2;

    /*package*/ final short Analog3;

    /*package*/ final short Analog4;

    /*package*/ final short Digital1;

    /*package*/ final short Digital2;

    public LensConfigS(
            short Analog1,
            short Analog2,
            short Analog3,
            short Analog4,
            short Digital1,
            short Digital2) {
        this.Analog1 = Analog1;
        this.Analog2 = Analog2;
        this.Analog3 = Analog3;
        this.Analog4 = Analog4;
        this.Digital1 = Digital1;
        this.Digital2 = Digital2;
    }

    public short getAnalog1() {
        return Analog1;
    }

    /** lens connected to analog video source 1 */
    public short getAnalog2() {
        return Analog2;
    }

    /** lens connected to analog video source 2 */
    public short getAnalog3() {
        return Analog3;
    }

    /**
     * lens connected to analog video source 3
     * (differential input on Model 6005 R2)
     */
    public short getAnalog4() {
        return Analog4;
    }

    /**
     * lens connected to analog video source 4
     * (not available on Model 6005 R2)
     */
    public short getDigital1() {
        return Digital1;
    }

    /**
     * lens connected to digital video source 1
     * lens connected to digital video source 2
     * (not available on Model 6005 and only
     *  supported on 6007 with daughter card)
     */
    public short getDigital2() {
        return Digital2;
    }

    @Override
    public String toString() {
        return "LensConfigS{" +
                "Analog1=" + Analog1 +
                "," + "Analog2=" + Analog2 +
                "," + "Analog3=" + Analog3 +
                "," + "Analog4=" + Analog4 +
                "," + "Digital1=" + Digital1 +
                "," + "Digital2=" + Digital2 +
        "}";
    }

}
