// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#import "EOAPILensSerialZoomS+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto LensSerialZoomS::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I16::toCpp(obj.LensType),
            ::djinni::I8::toCpp(obj.LensID),
            ::djinni::I8::toCpp(obj.VideoSource),
            ::djinni::I8::toCpp(obj.SerialPort),
            ::djinni::I8::toCpp(obj.ZoomCmd),
            ::djinni::I8::toCpp(obj.FocusCmd),
            ::djinni::I8::toCpp(obj.IrisCmd),
            ::djinni::I8::toCpp(obj.IrisAuto),
            ::djinni::I8::toCpp(obj.ZoomCal),
            ::djinni::I8::toCpp(obj.UseOldProtocol),
            ::djinni::I8::toCpp(obj.Enable2X),
            ::djinni::F64::toCpp(obj.ZoomFov),
            ::djinni::F64::toCpp(obj.MinFov),
            ::djinni::F64::toCpp(obj.MaxFov),
            ::djinni::I16::toCpp(obj.FocusPosition)};
}

auto LensSerialZoomS::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[EOAPILensSerialZoomS alloc] initWithLensType:(::djinni::I16::fromCpp(cpp.LensType))
                                                   LensID:(::djinni::I8::fromCpp(cpp.LensID))
                                              VideoSource:(::djinni::I8::fromCpp(cpp.VideoSource))
                                               SerialPort:(::djinni::I8::fromCpp(cpp.SerialPort))
                                                  ZoomCmd:(::djinni::I8::fromCpp(cpp.ZoomCmd))
                                                 FocusCmd:(::djinni::I8::fromCpp(cpp.FocusCmd))
                                                  IrisCmd:(::djinni::I8::fromCpp(cpp.IrisCmd))
                                                 IrisAuto:(::djinni::I8::fromCpp(cpp.IrisAuto))
                                                  ZoomCal:(::djinni::I8::fromCpp(cpp.ZoomCal))
                                           UseOldProtocol:(::djinni::I8::fromCpp(cpp.UseOldProtocol))
                                                 Enable2X:(::djinni::I8::fromCpp(cpp.Enable2X))
                                                  ZoomFov:(::djinni::F64::fromCpp(cpp.ZoomFov))
                                                   MinFov:(::djinni::F64::fromCpp(cpp.MinFov))
                                                   MaxFov:(::djinni::F64::fromCpp(cpp.MaxFov))
                                            FocusPosition:(::djinni::I16::fromCpp(cpp.FocusPosition))];
}

}  // namespace djinni_generated
