// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#import "EOAPILensSerialZoomS.h"


@implementation EOAPILensSerialZoomS

- (nonnull instancetype)initWithLensType:(int16_t)LensType
                                  LensID:(int8_t)LensID
                             VideoSource:(int8_t)VideoSource
                              SerialPort:(int8_t)SerialPort
                                 ZoomCmd:(int8_t)ZoomCmd
                                FocusCmd:(int8_t)FocusCmd
                                 IrisCmd:(int8_t)IrisCmd
                                IrisAuto:(int8_t)IrisAuto
                                 ZoomCal:(int8_t)ZoomCal
                          UseOldProtocol:(int8_t)UseOldProtocol
                                Enable2X:(int8_t)Enable2X
                                 ZoomFov:(double)ZoomFov
                                  MinFov:(double)MinFov
                                  MaxFov:(double)MaxFov
                           FocusPosition:(int16_t)FocusPosition
{
    if (self = [super init]) {
        _LensType = LensType;
        _LensID = LensID;
        _VideoSource = VideoSource;
        _SerialPort = SerialPort;
        _ZoomCmd = ZoomCmd;
        _FocusCmd = FocusCmd;
        _IrisCmd = IrisCmd;
        _IrisAuto = IrisAuto;
        _ZoomCal = ZoomCal;
        _UseOldProtocol = UseOldProtocol;
        _Enable2X = Enable2X;
        _ZoomFov = ZoomFov;
        _MinFov = MinFov;
        _MaxFov = MaxFov;
        _FocusPosition = FocusPosition;
    }
    return self;
}

+ (nonnull instancetype)LensSerialZoomSWithLensType:(int16_t)LensType
                                             LensID:(int8_t)LensID
                                        VideoSource:(int8_t)VideoSource
                                         SerialPort:(int8_t)SerialPort
                                            ZoomCmd:(int8_t)ZoomCmd
                                           FocusCmd:(int8_t)FocusCmd
                                            IrisCmd:(int8_t)IrisCmd
                                           IrisAuto:(int8_t)IrisAuto
                                            ZoomCal:(int8_t)ZoomCal
                                     UseOldProtocol:(int8_t)UseOldProtocol
                                           Enable2X:(int8_t)Enable2X
                                            ZoomFov:(double)ZoomFov
                                             MinFov:(double)MinFov
                                             MaxFov:(double)MaxFov
                                      FocusPosition:(int16_t)FocusPosition
{
    return [[self alloc] initWithLensType:LensType
                                   LensID:LensID
                              VideoSource:VideoSource
                               SerialPort:SerialPort
                                  ZoomCmd:ZoomCmd
                                 FocusCmd:FocusCmd
                                  IrisCmd:IrisCmd
                                 IrisAuto:IrisAuto
                                  ZoomCal:ZoomCal
                           UseOldProtocol:UseOldProtocol
                                 Enable2X:Enable2X
                                  ZoomFov:ZoomFov
                                   MinFov:MinFov
                                   MaxFov:MaxFov
                            FocusPosition:FocusPosition];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p LensType:%@ LensID:%@ VideoSource:%@ SerialPort:%@ ZoomCmd:%@ FocusCmd:%@ IrisCmd:%@ IrisAuto:%@ ZoomCal:%@ UseOldProtocol:%@ Enable2X:%@ ZoomFov:%@ MinFov:%@ MaxFov:%@ FocusPosition:%@>", self.class, (void *)self, @(self.LensType), @(self.LensID), @(self.VideoSource), @(self.SerialPort), @(self.ZoomCmd), @(self.FocusCmd), @(self.IrisCmd), @(self.IrisAuto), @(self.ZoomCal), @(self.UseOldProtocol), @(self.Enable2X), @(self.ZoomFov), @(self.MinFov), @(self.MaxFov), @(self.FocusPosition)];
}

@end
