// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#import "EOAPILensConfigS.h"
#import "EOAPILensSerialIRZoomS.h"
#import "EOAPILensSerialZoomS.h"
#import "EOAPIZoomToRangeConfigS.h"
#import <Foundation/Foundation.h>


@interface EOAPIEOAPILib : NSObject

+ (void)ILens;

- (void)SetSerialZoom:(nonnull EOAPILensSerialZoomS *)zoom;

- (int16_t)QueryAllLensConfig:(int16_t)serialIRType;

- (nonnull EOAPILensSerialZoomS *)ParseSerialZoomConfigMessage:(int8_t)data;

- (void)SetSerialIRZoom:(nonnull EOAPILensSerialIRZoomS *)zoom;

- (nonnull EOAPILensSerialIRZoomS *)ParseSerialIRZoomConfigMessage:(int8_t)data;

- (void)SetZoomToRange:(nonnull EOAPIZoomToRangeConfigS *)config;

- (nonnull EOAPIZoomToRangeConfigS *)ParseZoomToRangeConfigMessage:(int8_t)data;

- (void)SetConnectionID:(int16_t)connectionID;

- (void)SetLensConfig:(nonnull EOAPILensConfigS *)config;

- (nonnull EOAPILensConfigS *)ParseLensConfigMessage:(int8_t)data;

@end
