// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#import "EOAPILensConfigS.h"
#include "LensConfig_s.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class EOAPILensConfigS;

namespace djinni_generated {

struct LensConfigS
{
    using CppType = ::eo_api::LensConfigS;
    using ObjcType = EOAPILensConfigS*;

    using Boxed = LensConfigS;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
