// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#import "EOAPILensSerialIRZoomS+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto LensSerialIRZoomS::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I16::toCpp(obj.LensType),
            ::djinni::I8::toCpp(obj.VideoSource),
            ::djinni::I8::toCpp(obj.SerialPort),
            ::djinni::I8::toCpp(obj.ZoomCmd),
            ::djinni::I8::toCpp(obj.ZoomCal),
            ::djinni::I8::toCpp(obj.FocusCmd),
            ::djinni::I8::toCpp(obj.Polarity),
            ::djinni::I8::toCpp(obj.AGC),
            ::djinni::I8::toCpp(obj.DayMode),
            ::djinni::I8::toCpp(obj.HighSensitivity),
            ::djinni::I8::toCpp(obj.AutoCalibration),
            ::djinni::I8::toCpp(obj.LensCover),
            ::djinni::I8::toCpp(obj.FlirMenuCommand),
            ::djinni::I16::toCpp(obj.ManualGain),
            ::djinni::I16::toCpp(obj.ManualOffset),
            ::djinni::I16::toCpp(obj.NonUniformityCorrectionTable),
            ::djinni::F64::toCpp(obj.ZoomFov),
            ::djinni::F64::toCpp(obj.MinFov),
            ::djinni::F64::toCpp(obj.MaxFov),
            ::djinni::I16::toCpp(obj.FocusPosition)};
}

auto LensSerialIRZoomS::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[EOAPILensSerialIRZoomS alloc] initWithLensType:(::djinni::I16::fromCpp(cpp.LensType))
                                                VideoSource:(::djinni::I8::fromCpp(cpp.VideoSource))
                                                 SerialPort:(::djinni::I8::fromCpp(cpp.SerialPort))
                                                    ZoomCmd:(::djinni::I8::fromCpp(cpp.ZoomCmd))
                                                    ZoomCal:(::djinni::I8::fromCpp(cpp.ZoomCal))
                                                   FocusCmd:(::djinni::I8::fromCpp(cpp.FocusCmd))
                                                   Polarity:(::djinni::I8::fromCpp(cpp.Polarity))
                                                        AGC:(::djinni::I8::fromCpp(cpp.AGC))
                                                    DayMode:(::djinni::I8::fromCpp(cpp.DayMode))
                                            HighSensitivity:(::djinni::I8::fromCpp(cpp.HighSensitivity))
                                            AutoCalibration:(::djinni::I8::fromCpp(cpp.AutoCalibration))
                                                  LensCover:(::djinni::I8::fromCpp(cpp.LensCover))
                                            FlirMenuCommand:(::djinni::I8::fromCpp(cpp.FlirMenuCommand))
                                                 ManualGain:(::djinni::I16::fromCpp(cpp.ManualGain))
                                               ManualOffset:(::djinni::I16::fromCpp(cpp.ManualOffset))
                               NonUniformityCorrectionTable:(::djinni::I16::fromCpp(cpp.NonUniformityCorrectionTable))
                                                    ZoomFov:(::djinni::F64::fromCpp(cpp.ZoomFov))
                                                     MinFov:(::djinni::F64::fromCpp(cpp.MinFov))
                                                     MaxFov:(::djinni::F64::fromCpp(cpp.MaxFov))
                                              FocusPosition:(::djinni::I16::fromCpp(cpp.FocusPosition))];
}

}  // namespace djinni_generated
