// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#import <Foundation/Foundation.h>

/** EO_API.djinni : IDL source for EO_API */
@interface EOAPILensSerialZoomS : NSObject
- (nonnull instancetype)initWithLensType:(int16_t)LensType
                                  LensID:(int8_t)LensID
                             VideoSource:(int8_t)VideoSource
                              SerialPort:(int8_t)SerialPort
                                 ZoomCmd:(int8_t)ZoomCmd
                                FocusCmd:(int8_t)FocusCmd
                                 IrisCmd:(int8_t)IrisCmd
                                IrisAuto:(int8_t)IrisAuto
                                 ZoomCal:(int8_t)ZoomCal
                          UseOldProtocol:(int8_t)UseOldProtocol
                                Enable2X:(int8_t)Enable2X
                                 ZoomFov:(double)ZoomFov
                                  MinFov:(double)MinFov
                                  MaxFov:(double)MaxFov
                           FocusPosition:(int16_t)FocusPosition;
+ (nonnull instancetype)LensSerialZoomSWithLensType:(int16_t)LensType
                                             LensID:(int8_t)LensID
                                        VideoSource:(int8_t)VideoSource
                                         SerialPort:(int8_t)SerialPort
                                            ZoomCmd:(int8_t)ZoomCmd
                                           FocusCmd:(int8_t)FocusCmd
                                            IrisCmd:(int8_t)IrisCmd
                                           IrisAuto:(int8_t)IrisAuto
                                            ZoomCal:(int8_t)ZoomCal
                                     UseOldProtocol:(int8_t)UseOldProtocol
                                           Enable2X:(int8_t)Enable2X
                                            ZoomFov:(double)ZoomFov
                                             MinFov:(double)MinFov
                                             MaxFov:(double)MaxFov
                                      FocusPosition:(int16_t)FocusPosition;

@property (nonatomic, readonly) int16_t LensType;

/** lens type */
@property (nonatomic, readonly) int8_t LensID;

@property (nonatomic, readonly) int8_t VideoSource;

/** video source lens is connected to */
@property (nonatomic, readonly) int8_t SerialPort;

/** tracker serial port lens is connected to (3-7, 0-2 are reserved) */
@property (nonatomic, readonly) int8_t ZoomCmd;

/** zoom command (0=none, 1=narrow, 2=wide, 3=go to pos) */
@property (nonatomic, readonly) int8_t FocusCmd;

/** focus command (0=none, 1=near, 2=far, 3=go to pos) */
@property (nonatomic, readonly) int8_t IrisCmd;

/** iris command (0=none, 1=close, 2=open) */
@property (nonatomic, readonly) int8_t IrisAuto;

/** automatic iris (0=disabled, 1=enabled/automatic) */
@property (nonatomic, readonly) int8_t ZoomCal;

/** perform zoom scale calibration (1=run now) */
@property (nonatomic, readonly) int8_t UseOldProtocol;

/** use older lens communication protocol (LENS_COHU_MPC) */
@property (nonatomic, readonly) int8_t Enable2X;

/** enable 2X extender (LENS_FUJINON_D60) */
@property (nonatomic, readonly) double ZoomFov;

/**
 * zoom field-of-view in degrees
 *   range: 0 to 360.00 (divide by 100 to get value)
 */
@property (nonatomic, readonly) double MinFov;

/**
 * minimum zoom field-of-view of the lens in degrees
 *   range: 0 to 360.00 (divide by 100 to get value)
 */
@property (nonatomic, readonly) double MaxFov;

/**
 * maximum zoom field-of-view of the lens in degrees
 *   range: 0 to 360.00 (divide by 100 to get value)
 * focus position
 */
@property (nonatomic, readonly) int16_t FocusPosition;

@end
