// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#import "EOAPILensSerialZoomS.h"
#include "LensSerialZoom_s.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class EOAPILensSerialZoomS;

namespace djinni_generated {

struct LensSerialZoomS
{
    using CppType = ::eo_api::LensSerialZoomS;
    using ObjcType = EOAPILensSerialZoomS*;

    using Boxed = LensSerialZoomS;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
