// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#import "EOAPIZoomToRangeConfigS.h"


@implementation EOAPIZoomToRangeConfigS

- (nonnull instancetype)initWithVideoSource:(int16_t)VideoSource
                                     Enable:(int16_t)Enable
                    UseSinglePointAlgorithm:(int8_t)UseSinglePointAlgorithm
                                 MinLensFOV:(double)MinLensFOV
                                 MaxLensFOV:(double)MaxLensFOV
                                   MinRange:(int16_t)MinRange
                                   MaxRange:(int16_t)MaxRange
{
    if (self = [super init]) {
        _VideoSource = VideoSource;
        _Enable = Enable;
        _UseSinglePointAlgorithm = UseSinglePointAlgorithm;
        _MinLensFOV = MinLensFOV;
        _MaxLensFOV = MaxLensFOV;
        _MinRange = MinRange;
        _MaxRange = MaxRange;
    }
    return self;
}

+ (nonnull instancetype)ZoomToRangeConfigSWithVideoSource:(int16_t)VideoSource
                                                   Enable:(int16_t)Enable
                                  UseSinglePointAlgorithm:(int8_t)UseSinglePointAlgorithm
                                               MinLensFOV:(double)MinLensFOV
                                               MaxLensFOV:(double)MaxLensFOV
                                                 MinRange:(int16_t)MinRange
                                                 MaxRange:(int16_t)MaxRange
{
    return [[self alloc] initWithVideoSource:VideoSource
                                      Enable:Enable
                     UseSinglePointAlgorithm:UseSinglePointAlgorithm
                                  MinLensFOV:MinLensFOV
                                  MaxLensFOV:MaxLensFOV
                                    MinRange:MinRange
                                    MaxRange:MaxRange];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p VideoSource:%@ Enable:%@ UseSinglePointAlgorithm:%@ MinLensFOV:%@ MaxLensFOV:%@ MinRange:%@ MaxRange:%@>", self.class, (void *)self, @(self.VideoSource), @(self.Enable), @(self.UseSinglePointAlgorithm), @(self.MinLensFOV), @(self.MaxLensFOV), @(self.MinRange), @(self.MaxRange)];
}

@end
