// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#import "HWLensConfigS.h"
#import "HWLensSerialIRZoomS.h"
#import "HWLensSerialZoomS.h"
#import "HWZoomToRangeConfigS.h"
#import <Foundation/Foundation.h>


@interface HWEOAPILib : NSObject

+ (void)ILens;

- (void)SetSerialZoom:(nonnull HWLensSerialZoomS *)zoom;

- (int16_t)QueryAllLensConfig:(int16_t)serialIRType;

- (nonnull HWLensSerialZoomS *)ParseSerialZoomConfigMessage:(int8_t)data;

- (void)SetSerialIRZoom:(nonnull HWLensSerialIRZoomS *)zoom;

- (nonnull HWLensSerialIRZoomS *)ParseSerialIRZoomConfigMessage:(int8_t)data;

- (void)SetZoomToRange:(nonnull HWZoomToRangeConfigS *)config;

- (nonnull HWZoomToRangeConfigS *)ParseZoomToRangeConfigMessage:(int8_t)data;

- (void)SetConnectionID:(int16_t)connectionID;

- (void)SetLensConfig:(nonnull HWLensConfigS *)config;

- (nonnull HWLensConfigS *)ParseLensConfigMessage:(int8_t)data;

@end
