// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#import <Foundation/Foundation.h>

/** ---------- Lens Config Message Structure ---------- */
@interface HWLensConfigS : NSObject
- (nonnull instancetype)initWithAnalog1:(int16_t)Analog1
                                Analog2:(int16_t)Analog2
                                Analog3:(int16_t)Analog3
                                Analog4:(int16_t)Analog4
                               Digital1:(int16_t)Digital1
                               Digital2:(int16_t)Digital2;
+ (nonnull instancetype)LensConfigSWithAnalog1:(int16_t)Analog1
                                       Analog2:(int16_t)Analog2
                                       Analog3:(int16_t)Analog3
                                       Analog4:(int16_t)Analog4
                                      Digital1:(int16_t)Digital1
                                      Digital2:(int16_t)Digital2;

@property (nonatomic, readonly) int16_t Analog1;

/** lens connected to analog video source 1 */
@property (nonatomic, readonly) int16_t Analog2;

/** lens connected to analog video source 2 */
@property (nonatomic, readonly) int16_t Analog3;

/**
 * lens connected to analog video source 3
 * (differential input on Model 6005 R2)
 */
@property (nonatomic, readonly) int16_t Analog4;

/**
 * lens connected to analog video source 4
 * (not available on Model 6005 R2)
 */
@property (nonatomic, readonly) int16_t Digital1;

/**
 * lens connected to digital video source 1
 * lens connected to digital video source 2
 * (not available on Model 6005 and only
 *  supported on 6007 with daughter card)
 */
@property (nonatomic, readonly) int16_t Digital2;

@end
