// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#import "HWLensSerialZoomS.h"
#include "LensSerialZoom_s.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class HWLensSerialZoomS;

namespace djinni_generated {

struct LensSerialZoomS
{
    using CppType = ::helloworld::LensSerialZoomS;
    using ObjcType = HWLensSerialZoomS*;

    using Boxed = LensSerialZoomS;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
