// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#import "HWLensConfigS.h"


@implementation HWLensConfigS

- (nonnull instancetype)initWithAnalog1:(int16_t)Analog1
                                Analog2:(int16_t)Analog2
                                Analog3:(int16_t)Analog3
                                Analog4:(int16_t)Analog4
                               Digital1:(int16_t)Digital1
                               Digital2:(int16_t)Digital2
{
    if (self = [super init]) {
        _Analog1 = Analog1;
        _Analog2 = Analog2;
        _Analog3 = Analog3;
        _Analog4 = Analog4;
        _Digital1 = Digital1;
        _Digital2 = Digital2;
    }
    return self;
}

+ (nonnull instancetype)LensConfigSWithAnalog1:(int16_t)Analog1
                                       Analog2:(int16_t)Analog2
                                       Analog3:(int16_t)Analog3
                                       Analog4:(int16_t)Analog4
                                      Digital1:(int16_t)Digital1
                                      Digital2:(int16_t)Digital2
{
    return [[self alloc] initWithAnalog1:Analog1
                                 Analog2:Analog2
                                 Analog3:Analog3
                                 Analog4:Analog4
                                Digital1:Digital1
                                Digital2:Digital2];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p Analog1:%@ Analog2:%@ Analog3:%@ Analog4:%@ Digital1:%@ Digital2:%@>", self.class, (void *)self, @(self.Analog1), @(self.Analog2), @(self.Analog3), @(self.Analog4), @(self.Digital1), @(self.Digital2)];
}

@end
