// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#import "HWLensSerialIRZoomS.h"
#include "LensSerialIRZoom_s.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class HWLensSerialIRZoomS;

namespace djinni_generated {

struct LensSerialIRZoomS
{
    using CppType = ::helloworld::LensSerialIRZoomS;
    using ObjcType = HWLensSerialIRZoomS*;

    using Boxed = LensSerialIRZoomS;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
