// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#import "HWLensConfigS+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto LensConfigS::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I16::toCpp(obj.Analog1),
            ::djinni::I16::toCpp(obj.Analog2),
            ::djinni::I16::toCpp(obj.Analog3),
            ::djinni::I16::toCpp(obj.Analog4),
            ::djinni::I16::toCpp(obj.Digital1),
            ::djinni::I16::toCpp(obj.Digital2)};
}

auto LensConfigS::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[HWLensConfigS alloc] initWithAnalog1:(::djinni::I16::fromCpp(cpp.Analog1))
                                          Analog2:(::djinni::I16::fromCpp(cpp.Analog2))
                                          Analog3:(::djinni::I16::fromCpp(cpp.Analog3))
                                          Analog4:(::djinni::I16::fromCpp(cpp.Analog4))
                                         Digital1:(::djinni::I16::fromCpp(cpp.Digital1))
                                         Digital2:(::djinni::I16::fromCpp(cpp.Digital2))];
}

}  // namespace djinni_generated
