// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#import "HWZoomToRangeConfigS.h"
#include "ZoomToRangeConfig_s.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class HWZoomToRangeConfigS;

namespace djinni_generated {

struct ZoomToRangeConfigS
{
    using CppType = ::helloworld::ZoomToRangeConfigS;
    using ObjcType = HWZoomToRangeConfigS*;

    using Boxed = ZoomToRangeConfigS;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
