// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from EO_API.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace eo_api {

/** EO_API.djinni : IDL source for EO_API */
struct LensSerialZoomS final {
    int16_t LensType;
    /** lens type */
    int8_t LensID;
    int8_t VideoSource;
    /** video source lens is connected to */
    int8_t SerialPort;
    /** tracker serial port lens is connected to (3-7, 0-2 are reserved) */
    int8_t ZoomCmd;
    /** zoom command (0=none, 1=narrow, 2=wide, 3=go to pos) */
    int8_t FocusCmd;
    /** focus command (0=none, 1=near, 2=far, 3=go to pos) */
    int8_t IrisCmd;
    /** iris command (0=none, 1=close, 2=open) */
    int8_t IrisAuto;
    /** automatic iris (0=disabled, 1=enabled/automatic) */
    int8_t ZoomCal;
    /** perform zoom scale calibration (1=run now) */
    int8_t UseOldProtocol;
    /** use older lens communication protocol (LENS_COHU_MPC) */
    int8_t Enable2X;
    /** enable 2X extender (LENS_FUJINON_D60) */
    double ZoomFov;
    /**
     * zoom field-of-view in degrees
     *   range: 0 to 360.00 (divide by 100 to get value)
     */
    double MinFov;
    /**
     * minimum zoom field-of-view of the lens in degrees
     *   range: 0 to 360.00 (divide by 100 to get value)
     */
    double MaxFov;
    /**
     * maximum zoom field-of-view of the lens in degrees
     *   range: 0 to 360.00 (divide by 100 to get value)
     * focus position
     */
    int16_t FocusPosition;

    LensSerialZoomS(int16_t LensType_,
                    int8_t LensID_,
                    int8_t VideoSource_,
                    int8_t SerialPort_,
                    int8_t ZoomCmd_,
                    int8_t FocusCmd_,
                    int8_t IrisCmd_,
                    int8_t IrisAuto_,
                    int8_t ZoomCal_,
                    int8_t UseOldProtocol_,
                    int8_t Enable2X_,
                    double ZoomFov_,
                    double MinFov_,
                    double MaxFov_,
                    int16_t FocusPosition_)
    : LensType(std::move(LensType_))
    , LensID(std::move(LensID_))
    , VideoSource(std::move(VideoSource_))
    , SerialPort(std::move(SerialPort_))
    , ZoomCmd(std::move(ZoomCmd_))
    , FocusCmd(std::move(FocusCmd_))
    , IrisCmd(std::move(IrisCmd_))
    , IrisAuto(std::move(IrisAuto_))
    , ZoomCal(std::move(ZoomCal_))
    , UseOldProtocol(std::move(UseOldProtocol_))
    , Enable2X(std::move(Enable2X_))
    , ZoomFov(std::move(ZoomFov_))
    , MinFov(std::move(MinFov_))
    , MaxFov(std::move(MaxFov_))
    , FocusPosition(std::move(FocusPosition_))
    {}
};

}  // namespace eo_api
